name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile --non-interactive
#      - name: Build
#        run: yarn build
#        env:
#          NODE_ENV: production
      - name: Test
        run: yarn test
