name: Build

on: [push, pull_request]

jobs:
  build:
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node_version: [
          10.x, # EOL: April 2021
          12.x, # EOL: April 2022
        ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: yarn --frozen-lockfile --non-interactive
#      - name: Build
#        run: yarn build
#        env:
#          NODE_ENV: production
      - name: Test
        run: yarn test
